webtalk_init -webtalk_dir C:/Users/Virtual Machine/project_reti_logiche/project_reti_logiche.sim/sim_1/synth/timing/xsim/xsim.dir/project_tb_time_synth/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Feb 23 15:09:47 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.3.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2035080" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "46a70f05-e179-4e21-8ae0-2cdcf1609966" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "c7b95cec9be644aea3e4dde786b8c2cc" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "8" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2494 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "4.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "2797500 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.34_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "16596_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2013867185 -regid "" -xml C:/Users/Virtual Machine/project_reti_logiche/project_reti_logiche.sim/sim_1/synth/timing/xsim/xsim.dir/project_tb_time_synth/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Virtual Machine/project_reti_logiche/project_reti_logiche.sim/sim_1/synth/timing/xsim/xsim.dir/project_tb_time_synth/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Virtual Machine/project_reti_logiche/project_reti_logiche.sim/sim_1/synth/timing/xsim/xsim.dir/project_tb_time_synth/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
